// Curated catalog of all 30/32 teams across MLB/NFL/NBA/NHL for the Sports Zone's
// Teams of Interest picker — a static multi-select rather than a live ESPN
// team-search integration. Pulled directly from ESPN's own team-list endpoint
// (site.api.espn.com/apis/site/v2/sports/{sport}/{league}/teams) so ids match
// exactly what lib/scores/espn.ts's per-team schedule fetch expects.

import type { TeamOfInterest } from './espn'

export const TEAM_CATALOG: TeamOfInterest[] = [
  // MLB
  { league: 'mlb', teamId: '29', name: 'Arizona Diamondbacks', shortName: 'Diamondbacks', abbrev: 'ARI' },
  { league: 'mlb', teamId: '11', name: 'Athletics', shortName: 'Athletics', abbrev: 'ATH' },
  { league: 'mlb', teamId: '15', name: 'Atlanta Braves', shortName: 'Braves', abbrev: 'ATL' },
  { league: 'mlb', teamId: '1', name: 'Baltimore Orioles', shortName: 'Orioles', abbrev: 'BAL' },
  { league: 'mlb', teamId: '2', name: 'Boston Red Sox', shortName: 'Red Sox', abbrev: 'BOS' },
  { league: 'mlb', teamId: '16', name: 'Chicago Cubs', shortName: 'Cubs', abbrev: 'CHC' },
  { league: 'mlb', teamId: '4', name: 'Chicago White Sox', shortName: 'White Sox', abbrev: 'CHW' },
  { league: 'mlb', teamId: '17', name: 'Cincinnati Reds', shortName: 'Reds', abbrev: 'CIN' },
  { league: 'mlb', teamId: '5', name: 'Cleveland Guardians', shortName: 'Guardians', abbrev: 'CLE' },
  { league: 'mlb', teamId: '27', name: 'Colorado Rockies', shortName: 'Rockies', abbrev: 'COL' },
  { league: 'mlb', teamId: '6', name: 'Detroit Tigers', shortName: 'Tigers', abbrev: 'DET' },
  { league: 'mlb', teamId: '18', name: 'Houston Astros', shortName: 'Astros', abbrev: 'HOU' },
  { league: 'mlb', teamId: '7', name: 'Kansas City Royals', shortName: 'Royals', abbrev: 'KC' },
  { league: 'mlb', teamId: '3', name: 'Los Angeles Angels', shortName: 'Angels', abbrev: 'LAA' },
  { league: 'mlb', teamId: '19', name: 'Los Angeles Dodgers', shortName: 'Dodgers', abbrev: 'LAD' },
  { league: 'mlb', teamId: '28', name: 'Miami Marlins', shortName: 'Marlins', abbrev: 'MIA' },
  { league: 'mlb', teamId: '8', name: 'Milwaukee Brewers', shortName: 'Brewers', abbrev: 'MIL' },
  { league: 'mlb', teamId: '9', name: 'Minnesota Twins', shortName: 'Twins', abbrev: 'MIN' },
  { league: 'mlb', teamId: '21', name: 'New York Mets', shortName: 'Mets', abbrev: 'NYM' },
  { league: 'mlb', teamId: '10', name: 'New York Yankees', shortName: 'Yankees', abbrev: 'NYY' },
  { league: 'mlb', teamId: '22', name: 'Philadelphia Phillies', shortName: 'Phillies', abbrev: 'PHI' },
  { league: 'mlb', teamId: '23', name: 'Pittsburgh Pirates', shortName: 'Pirates', abbrev: 'PIT' },
  { league: 'mlb', teamId: '25', name: 'San Diego Padres', shortName: 'Padres', abbrev: 'SD' },
  { league: 'mlb', teamId: '26', name: 'San Francisco Giants', shortName: 'Giants', abbrev: 'SF' },
  { league: 'mlb', teamId: '12', name: 'Seattle Mariners', shortName: 'Mariners', abbrev: 'SEA' },
  { league: 'mlb', teamId: '24', name: 'St. Louis Cardinals', shortName: 'Cardinals', abbrev: 'STL' },
  { league: 'mlb', teamId: '30', name: 'Tampa Bay Rays', shortName: 'Rays', abbrev: 'TB' },
  { league: 'mlb', teamId: '13', name: 'Texas Rangers', shortName: 'Rangers', abbrev: 'TEX' },
  { league: 'mlb', teamId: '14', name: 'Toronto Blue Jays', shortName: 'Blue Jays', abbrev: 'TOR' },
  { league: 'mlb', teamId: '20', name: 'Washington Nationals', shortName: 'Nationals', abbrev: 'WSH' },
  // NFL
  { league: 'nfl', teamId: '22', name: 'Arizona Cardinals', shortName: 'Cardinals', abbrev: 'ARI' },
  { league: 'nfl', teamId: '1', name: 'Atlanta Falcons', shortName: 'Falcons', abbrev: 'ATL' },
  { league: 'nfl', teamId: '33', name: 'Baltimore Ravens', shortName: 'Ravens', abbrev: 'BAL' },
  { league: 'nfl', teamId: '2', name: 'Buffalo Bills', shortName: 'Bills', abbrev: 'BUF' },
  { league: 'nfl', teamId: '29', name: 'Carolina Panthers', shortName: 'Panthers', abbrev: 'CAR' },
  { league: 'nfl', teamId: '3', name: 'Chicago Bears', shortName: 'Bears', abbrev: 'CHI' },
  { league: 'nfl', teamId: '4', name: 'Cincinnati Bengals', shortName: 'Bengals', abbrev: 'CIN' },
  { league: 'nfl', teamId: '5', name: 'Cleveland Browns', shortName: 'Browns', abbrev: 'CLE' },
  { league: 'nfl', teamId: '6', name: 'Dallas Cowboys', shortName: 'Cowboys', abbrev: 'DAL' },
  { league: 'nfl', teamId: '7', name: 'Denver Broncos', shortName: 'Broncos', abbrev: 'DEN' },
  { league: 'nfl', teamId: '8', name: 'Detroit Lions', shortName: 'Lions', abbrev: 'DET' },
  { league: 'nfl', teamId: '9', name: 'Green Bay Packers', shortName: 'Packers', abbrev: 'GB' },
  { league: 'nfl', teamId: '34', name: 'Houston Texans', shortName: 'Texans', abbrev: 'HOU' },
  { league: 'nfl', teamId: '11', name: 'Indianapolis Colts', shortName: 'Colts', abbrev: 'IND' },
  { league: 'nfl', teamId: '30', name: 'Jacksonville Jaguars', shortName: 'Jaguars', abbrev: 'JAX' },
  { league: 'nfl', teamId: '12', name: 'Kansas City Chiefs', shortName: 'Chiefs', abbrev: 'KC' },
  { league: 'nfl', teamId: '13', name: 'Las Vegas Raiders', shortName: 'Raiders', abbrev: 'LV' },
  { league: 'nfl', teamId: '24', name: 'Los Angeles Chargers', shortName: 'Chargers', abbrev: 'LAC' },
  { league: 'nfl', teamId: '14', name: 'Los Angeles Rams', shortName: 'Rams', abbrev: 'LAR' },
  { league: 'nfl', teamId: '15', name: 'Miami Dolphins', shortName: 'Dolphins', abbrev: 'MIA' },
  { league: 'nfl', teamId: '16', name: 'Minnesota Vikings', shortName: 'Vikings', abbrev: 'MIN' },
  { league: 'nfl', teamId: '17', name: 'New England Patriots', shortName: 'Patriots', abbrev: 'NE' },
  { league: 'nfl', teamId: '18', name: 'New Orleans Saints', shortName: 'Saints', abbrev: 'NO' },
  { league: 'nfl', teamId: '19', name: 'New York Giants', shortName: 'Giants', abbrev: 'NYG' },
  { league: 'nfl', teamId: '20', name: 'New York Jets', shortName: 'Jets', abbrev: 'NYJ' },
  { league: 'nfl', teamId: '21', name: 'Philadelphia Eagles', shortName: 'Eagles', abbrev: 'PHI' },
  { league: 'nfl', teamId: '23', name: 'Pittsburgh Steelers', shortName: 'Steelers', abbrev: 'PIT' },
  { league: 'nfl', teamId: '25', name: 'San Francisco 49ers', shortName: '49ers', abbrev: 'SF' },
  { league: 'nfl', teamId: '26', name: 'Seattle Seahawks', shortName: 'Seahawks', abbrev: 'SEA' },
  { league: 'nfl', teamId: '27', name: 'Tampa Bay Buccaneers', shortName: 'Buccaneers', abbrev: 'TB' },
  { league: 'nfl', teamId: '10', name: 'Tennessee Titans', shortName: 'Titans', abbrev: 'TEN' },
  { league: 'nfl', teamId: '28', name: 'Washington Commanders', shortName: 'Commanders', abbrev: 'WSH' },
  // NBA
  { league: 'nba', teamId: '1', name: 'Atlanta Hawks', shortName: 'Hawks', abbrev: 'ATL' },
  { league: 'nba', teamId: '2', name: 'Boston Celtics', shortName: 'Celtics', abbrev: 'BOS' },
  { league: 'nba', teamId: '17', name: 'Brooklyn Nets', shortName: 'Nets', abbrev: 'BKN' },
  { league: 'nba', teamId: '30', name: 'Charlotte Hornets', shortName: 'Hornets', abbrev: 'CHA' },
  { league: 'nba', teamId: '4', name: 'Chicago Bulls', shortName: 'Bulls', abbrev: 'CHI' },
  { league: 'nba', teamId: '5', name: 'Cleveland Cavaliers', shortName: 'Cavaliers', abbrev: 'CLE' },
  { league: 'nba', teamId: '6', name: 'Dallas Mavericks', shortName: 'Mavericks', abbrev: 'DAL' },
  { league: 'nba', teamId: '7', name: 'Denver Nuggets', shortName: 'Nuggets', abbrev: 'DEN' },
  { league: 'nba', teamId: '8', name: 'Detroit Pistons', shortName: 'Pistons', abbrev: 'DET' },
  { league: 'nba', teamId: '9', name: 'Golden State Warriors', shortName: 'Warriors', abbrev: 'GS' },
  { league: 'nba', teamId: '10', name: 'Houston Rockets', shortName: 'Rockets', abbrev: 'HOU' },
  { league: 'nba', teamId: '11', name: 'Indiana Pacers', shortName: 'Pacers', abbrev: 'IND' },
  { league: 'nba', teamId: '12', name: 'LA Clippers', shortName: 'Clippers', abbrev: 'LAC' },
  { league: 'nba', teamId: '13', name: 'Los Angeles Lakers', shortName: 'Lakers', abbrev: 'LAL' },
  { league: 'nba', teamId: '29', name: 'Memphis Grizzlies', shortName: 'Grizzlies', abbrev: 'MEM' },
  { league: 'nba', teamId: '14', name: 'Miami Heat', shortName: 'Heat', abbrev: 'MIA' },
  { league: 'nba', teamId: '15', name: 'Milwaukee Bucks', shortName: 'Bucks', abbrev: 'MIL' },
  { league: 'nba', teamId: '16', name: 'Minnesota Timberwolves', shortName: 'Timberwolves', abbrev: 'MIN' },
  { league: 'nba', teamId: '3', name: 'New Orleans Pelicans', shortName: 'Pelicans', abbrev: 'NO' },
  { league: 'nba', teamId: '18', name: 'New York Knicks', shortName: 'Knicks', abbrev: 'NY' },
  { league: 'nba', teamId: '25', name: 'Oklahoma City Thunder', shortName: 'Thunder', abbrev: 'OKC' },
  { league: 'nba', teamId: '19', name: 'Orlando Magic', shortName: 'Magic', abbrev: 'ORL' },
  { league: 'nba', teamId: '20', name: 'Philadelphia 76ers', shortName: '76ers', abbrev: 'PHI' },
  { league: 'nba', teamId: '21', name: 'Phoenix Suns', shortName: 'Suns', abbrev: 'PHX' },
  { league: 'nba', teamId: '22', name: 'Portland Trail Blazers', shortName: 'Trail Blazers', abbrev: 'POR' },
  { league: 'nba', teamId: '23', name: 'Sacramento Kings', shortName: 'Kings', abbrev: 'SAC' },
  { league: 'nba', teamId: '24', name: 'San Antonio Spurs', shortName: 'Spurs', abbrev: 'SA' },
  { league: 'nba', teamId: '28', name: 'Toronto Raptors', shortName: 'Raptors', abbrev: 'TOR' },
  { league: 'nba', teamId: '26', name: 'Utah Jazz', shortName: 'Jazz', abbrev: 'UTAH' },
  { league: 'nba', teamId: '27', name: 'Washington Wizards', shortName: 'Wizards', abbrev: 'WSH' },
  // NHL
  { league: 'nhl', teamId: '25', name: 'Anaheim Ducks', shortName: 'Ducks', abbrev: 'ANA' },
  { league: 'nhl', teamId: '1', name: 'Boston Bruins', shortName: 'Bruins', abbrev: 'BOS' },
  { league: 'nhl', teamId: '2', name: 'Buffalo Sabres', shortName: 'Sabres', abbrev: 'BUF' },
  { league: 'nhl', teamId: '3', name: 'Calgary Flames', shortName: 'Flames', abbrev: 'CGY' },
  { league: 'nhl', teamId: '7', name: 'Carolina Hurricanes', shortName: 'Hurricanes', abbrev: 'CAR' },
  { league: 'nhl', teamId: '4', name: 'Chicago Blackhawks', shortName: 'Blackhawks', abbrev: 'CHI' },
  { league: 'nhl', teamId: '17', name: 'Colorado Avalanche', shortName: 'Avalanche', abbrev: 'COL' },
  { league: 'nhl', teamId: '29', name: 'Columbus Blue Jackets', shortName: 'Blue Jackets', abbrev: 'CBJ' },
  { league: 'nhl', teamId: '9', name: 'Dallas Stars', shortName: 'Stars', abbrev: 'DAL' },
  { league: 'nhl', teamId: '5', name: 'Detroit Red Wings', shortName: 'Red Wings', abbrev: 'DET' },
  { league: 'nhl', teamId: '6', name: 'Edmonton Oilers', shortName: 'Oilers', abbrev: 'EDM' },
  { league: 'nhl', teamId: '26', name: 'Florida Panthers', shortName: 'Panthers', abbrev: 'FLA' },
  { league: 'nhl', teamId: '8', name: 'Los Angeles Kings', shortName: 'Kings', abbrev: 'LA' },
  { league: 'nhl', teamId: '30', name: 'Minnesota Wild', shortName: 'Wild', abbrev: 'MIN' },
  { league: 'nhl', teamId: '10', name: 'Montreal Canadiens', shortName: 'Canadiens', abbrev: 'MTL' },
  { league: 'nhl', teamId: '27', name: 'Nashville Predators', shortName: 'Predators', abbrev: 'NSH' },
  { league: 'nhl', teamId: '11', name: 'New Jersey Devils', shortName: 'Devils', abbrev: 'NJ' },
  { league: 'nhl', teamId: '12', name: 'New York Islanders', shortName: 'Islanders', abbrev: 'NYI' },
  { league: 'nhl', teamId: '13', name: 'New York Rangers', shortName: 'Rangers', abbrev: 'NYR' },
  { league: 'nhl', teamId: '14', name: 'Ottawa Senators', shortName: 'Senators', abbrev: 'OTT' },
  { league: 'nhl', teamId: '15', name: 'Philadelphia Flyers', shortName: 'Flyers', abbrev: 'PHI' },
  { league: 'nhl', teamId: '16', name: 'Pittsburgh Penguins', shortName: 'Penguins', abbrev: 'PIT' },
  { league: 'nhl', teamId: '18', name: 'San Jose Sharks', shortName: 'Sharks', abbrev: 'SJ' },
  { league: 'nhl', teamId: '124292', name: 'Seattle Kraken', shortName: 'Kraken', abbrev: 'SEA' },
  { league: 'nhl', teamId: '19', name: 'St. Louis Blues', shortName: 'Blues', abbrev: 'STL' },
  { league: 'nhl', teamId: '20', name: 'Tampa Bay Lightning', shortName: 'Lightning', abbrev: 'TB' },
  { league: 'nhl', teamId: '21', name: 'Toronto Maple Leafs', shortName: 'Maple Leafs', abbrev: 'TOR' },
  { league: 'nhl', teamId: '129764', name: 'Utah Mammoth', shortName: 'Mammoth', abbrev: 'UTAH' },
  { league: 'nhl', teamId: '22', name: 'Vancouver Canucks', shortName: 'Canucks', abbrev: 'VAN' },
  { league: 'nhl', teamId: '37', name: 'Vegas Golden Knights', shortName: 'Golden Knights', abbrev: 'VGK' },
  { league: 'nhl', teamId: '23', name: 'Washington Capitals', shortName: 'Capitals', abbrev: 'WSH' },
  { league: 'nhl', teamId: '28', name: 'Winnipeg Jets', shortName: 'Jets', abbrev: 'WPG' },
]

export const LEAGUE_LABELS: Record<TeamOfInterest['league'], string> = {
  mlb: 'MLB',
  nfl: 'NFL',
  nba: 'NBA',
  nhl: 'NHL',
}
